"""add policy column

Revision ID: 1ff1c1f7363b
Revises: 9f614c26f4fc
Create Date: 2026-04-04 08:01:14.981066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ff1c1f7363b'
down_revision: Union[str, Sequence[str], None] = '9f614c26f4fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('policy', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'policy')
    # ### end Alembic commands ###
