"""initial

Revision ID: 9f614c26f4fc
Revises: 
Create Date: 2026-04-04 07:56:47.598840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f614c26f4fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image_uri', sa.String(), nullable=True),
    sa.Column('strategy_type', sa.String(), nullable=False),
    sa.Column('strategy_prompt', sa.String(), nullable=False),
    sa.Column('pkey', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('tx_hash', sa.String(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('token_in', sa.String(), nullable=False),
    sa.Column('token_out', sa.String(), nullable=False),
    sa.Column('amount_in', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('amount_out', sa.Numeric(precision=78, scale=0), nullable=True),
    sa.Column('value_usd', sa.DECIMAL(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('tx_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('tx_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('agents')
    # ### end Alembic commands ###
